package cn.kuqi.Pojo;

public class Advertising {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.AD_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer adNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.AD_Title
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String adTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertising.AD_Code
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String adCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.AD_Number
     *
     * @return the value of advertising.AD_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getAdNumber() {
        return adNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.AD_Number
     *
     * @param adNumber the value for advertising.AD_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setAdNumber(Integer adNumber) {
        this.adNumber = adNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.AD_Title
     *
     * @return the value of advertising.AD_Title
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getAdTitle() {
        return adTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.AD_Title
     *
     * @param adTitle the value for advertising.AD_Title
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setAdTitle(String adTitle) {
        this.adTitle = adTitle == null ? null : adTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertising.AD_Code
     *
     * @return the value of advertising.AD_Code
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getAdCode() {
        return adCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertising.AD_Code
     *
     * @param adCode the value for advertising.AD_Code
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setAdCode(String adCode) {
        this.adCode = adCode == null ? null : adCode.trim();
    }
}