package cn.kuqi.Pojo;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer aNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_ID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_Title
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String aTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_ViewCount
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer aViewcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_Praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer aPraise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_Trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer aTrample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_PublishTime
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String aPublishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_CollectedCount
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer aCollectedcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_Type
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer aType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_Status
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer aStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_CommentCount
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer aCommentcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.A_Content
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String aContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_Number
     *
     * @return the value of article.A_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getaNumber() {
        return aNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_Number
     *
     * @param aNumber the value for article.A_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaNumber(Integer aNumber) {
        this.aNumber = aNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_ID
     *
     * @return the value of article.A_ID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_ID
     *
     * @param aId the value for article.A_ID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_Title
     *
     * @return the value of article.A_Title
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getaTitle() {
        return aTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_Title
     *
     * @param aTitle the value for article.A_Title
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaTitle(String aTitle) {
        this.aTitle = aTitle == null ? null : aTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_ViewCount
     *
     * @return the value of article.A_ViewCount
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getaViewcount() {
        return aViewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_ViewCount
     *
     * @param aViewcount the value for article.A_ViewCount
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaViewcount(Integer aViewcount) {
        this.aViewcount = aViewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_Praise
     *
     * @return the value of article.A_Praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getaPraise() {
        return aPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_Praise
     *
     * @param aPraise the value for article.A_Praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaPraise(Integer aPraise) {
        this.aPraise = aPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_Trample
     *
     * @return the value of article.A_Trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getaTrample() {
        return aTrample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_Trample
     *
     * @param aTrample the value for article.A_Trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaTrample(Integer aTrample) {
        this.aTrample = aTrample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_PublishTime
     *
     * @return the value of article.A_PublishTime
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getaPublishtime() {
        return aPublishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_PublishTime
     *
     * @param aPublishtime the value for article.A_PublishTime
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaPublishtime(String aPublishtime) {
        this.aPublishtime = aPublishtime == null ? null : aPublishtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_CollectedCount
     *
     * @return the value of article.A_CollectedCount
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getaCollectedcount() {
        return aCollectedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_CollectedCount
     *
     * @param aCollectedcount the value for article.A_CollectedCount
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaCollectedcount(Integer aCollectedcount) {
        this.aCollectedcount = aCollectedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_Type
     *
     * @return the value of article.A_Type
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getaType() {
        return aType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_Type
     *
     * @param aType the value for article.A_Type
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaType(Integer aType) {
        this.aType = aType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_Status
     *
     * @return the value of article.A_Status
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getaStatus() {
        return aStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_Status
     *
     * @param aStatus the value for article.A_Status
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaStatus(Integer aStatus) {
        this.aStatus = aStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_CommentCount
     *
     * @return the value of article.A_CommentCount
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getaCommentcount() {
        return aCommentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_CommentCount
     *
     * @param aCommentcount the value for article.A_CommentCount
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaCommentcount(Integer aCommentcount) {
        this.aCommentcount = aCommentcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.A_Content
     *
     * @return the value of article.A_Content
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getaContent() {
        return aContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.A_Content
     *
     * @param aContent the value for article.A_Content
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setaContent(String aContent) {
        this.aContent = aContent == null ? null : aContent.trim();
    }
}