package cn.kuqi.Pojo;

import java.util.ArrayList;
import java.util.List;

public class ArticlePraiseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public ArticlePraiseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApNumberIsNull() {
            addCriterion("AP_Number is null");
            return (Criteria) this;
        }

        public Criteria andApNumberIsNotNull() {
            addCriterion("AP_Number is not null");
            return (Criteria) this;
        }

        public Criteria andApNumberEqualTo(Integer value) {
            addCriterion("AP_Number =", value, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApNumberNotEqualTo(Integer value) {
            addCriterion("AP_Number <>", value, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApNumberGreaterThan(Integer value) {
            addCriterion("AP_Number >", value, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("AP_Number >=", value, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApNumberLessThan(Integer value) {
            addCriterion("AP_Number <", value, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApNumberLessThanOrEqualTo(Integer value) {
            addCriterion("AP_Number <=", value, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApNumberIn(List<Integer> values) {
            addCriterion("AP_Number in", values, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApNumberNotIn(List<Integer> values) {
            addCriterion("AP_Number not in", values, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApNumberBetween(Integer value1, Integer value2) {
            addCriterion("AP_Number between", value1, value2, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("AP_Number not between", value1, value2, "apNumber");
            return (Criteria) this;
        }

        public Criteria andApUseridIsNull() {
            addCriterion("AP_UserID is null");
            return (Criteria) this;
        }

        public Criteria andApUseridIsNotNull() {
            addCriterion("AP_UserID is not null");
            return (Criteria) this;
        }

        public Criteria andApUseridEqualTo(Integer value) {
            addCriterion("AP_UserID =", value, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApUseridNotEqualTo(Integer value) {
            addCriterion("AP_UserID <>", value, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApUseridGreaterThan(Integer value) {
            addCriterion("AP_UserID >", value, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("AP_UserID >=", value, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApUseridLessThan(Integer value) {
            addCriterion("AP_UserID <", value, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApUseridLessThanOrEqualTo(Integer value) {
            addCriterion("AP_UserID <=", value, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApUseridIn(List<Integer> values) {
            addCriterion("AP_UserID in", values, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApUseridNotIn(List<Integer> values) {
            addCriterion("AP_UserID not in", values, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApUseridBetween(Integer value1, Integer value2) {
            addCriterion("AP_UserID between", value1, value2, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("AP_UserID not between", value1, value2, "apUserid");
            return (Criteria) this;
        }

        public Criteria andApArticleIsNull() {
            addCriterion("AP_Article is null");
            return (Criteria) this;
        }

        public Criteria andApArticleIsNotNull() {
            addCriterion("AP_Article is not null");
            return (Criteria) this;
        }

        public Criteria andApArticleEqualTo(Integer value) {
            addCriterion("AP_Article =", value, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApArticleNotEqualTo(Integer value) {
            addCriterion("AP_Article <>", value, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApArticleGreaterThan(Integer value) {
            addCriterion("AP_Article >", value, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApArticleGreaterThanOrEqualTo(Integer value) {
            addCriterion("AP_Article >=", value, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApArticleLessThan(Integer value) {
            addCriterion("AP_Article <", value, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApArticleLessThanOrEqualTo(Integer value) {
            addCriterion("AP_Article <=", value, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApArticleIn(List<Integer> values) {
            addCriterion("AP_Article in", values, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApArticleNotIn(List<Integer> values) {
            addCriterion("AP_Article not in", values, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApArticleBetween(Integer value1, Integer value2) {
            addCriterion("AP_Article between", value1, value2, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApArticleNotBetween(Integer value1, Integer value2) {
            addCriterion("AP_Article not between", value1, value2, "apArticle");
            return (Criteria) this;
        }

        public Criteria andApTimeIsNull() {
            addCriterion("AP_Time is null");
            return (Criteria) this;
        }

        public Criteria andApTimeIsNotNull() {
            addCriterion("AP_Time is not null");
            return (Criteria) this;
        }

        public Criteria andApTimeEqualTo(String value) {
            addCriterion("AP_Time =", value, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeNotEqualTo(String value) {
            addCriterion("AP_Time <>", value, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeGreaterThan(String value) {
            addCriterion("AP_Time >", value, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeGreaterThanOrEqualTo(String value) {
            addCriterion("AP_Time >=", value, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeLessThan(String value) {
            addCriterion("AP_Time <", value, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeLessThanOrEqualTo(String value) {
            addCriterion("AP_Time <=", value, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeLike(String value) {
            addCriterion("AP_Time like", value, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeNotLike(String value) {
            addCriterion("AP_Time not like", value, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeIn(List<String> values) {
            addCriterion("AP_Time in", values, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeNotIn(List<String> values) {
            addCriterion("AP_Time not in", values, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeBetween(String value1, String value2) {
            addCriterion("AP_Time between", value1, value2, "apTime");
            return (Criteria) this;
        }

        public Criteria andApTimeNotBetween(String value1, String value2) {
            addCriterion("AP_Time not between", value1, value2, "apTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_praise
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}