package cn.kuqi.Pojo;

import java.util.ArrayList;
import java.util.List;

public class ArticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public ArticleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andANumberIsNull() {
            addCriterion("A_Number is null");
            return (Criteria) this;
        }

        public Criteria andANumberIsNotNull() {
            addCriterion("A_Number is not null");
            return (Criteria) this;
        }

        public Criteria andANumberEqualTo(Integer value) {
            addCriterion("A_Number =", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberNotEqualTo(Integer value) {
            addCriterion("A_Number <>", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberGreaterThan(Integer value) {
            addCriterion("A_Number >", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("A_Number >=", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberLessThan(Integer value) {
            addCriterion("A_Number <", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberLessThanOrEqualTo(Integer value) {
            addCriterion("A_Number <=", value, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberIn(List<Integer> values) {
            addCriterion("A_Number in", values, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberNotIn(List<Integer> values) {
            addCriterion("A_Number not in", values, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberBetween(Integer value1, Integer value2) {
            addCriterion("A_Number between", value1, value2, "aNumber");
            return (Criteria) this;
        }

        public Criteria andANumberNotBetween(Integer value1, Integer value2) {
            addCriterion("A_Number not between", value1, value2, "aNumber");
            return (Criteria) this;
        }

        public Criteria andAIdIsNull() {
            addCriterion("A_ID is null");
            return (Criteria) this;
        }

        public Criteria andAIdIsNotNull() {
            addCriterion("A_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAIdEqualTo(Integer value) {
            addCriterion("A_ID =", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotEqualTo(Integer value) {
            addCriterion("A_ID <>", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThan(Integer value) {
            addCriterion("A_ID >", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("A_ID >=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThan(Integer value) {
            addCriterion("A_ID <", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdLessThanOrEqualTo(Integer value) {
            addCriterion("A_ID <=", value, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdIn(List<Integer> values) {
            addCriterion("A_ID in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotIn(List<Integer> values) {
            addCriterion("A_ID not in", values, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdBetween(Integer value1, Integer value2) {
            addCriterion("A_ID between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andAIdNotBetween(Integer value1, Integer value2) {
            addCriterion("A_ID not between", value1, value2, "aId");
            return (Criteria) this;
        }

        public Criteria andATitleIsNull() {
            addCriterion("A_Title is null");
            return (Criteria) this;
        }

        public Criteria andATitleIsNotNull() {
            addCriterion("A_Title is not null");
            return (Criteria) this;
        }

        public Criteria andATitleEqualTo(String value) {
            addCriterion("A_Title =", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleNotEqualTo(String value) {
            addCriterion("A_Title <>", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleGreaterThan(String value) {
            addCriterion("A_Title >", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleGreaterThanOrEqualTo(String value) {
            addCriterion("A_Title >=", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleLessThan(String value) {
            addCriterion("A_Title <", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleLessThanOrEqualTo(String value) {
            addCriterion("A_Title <=", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleLike(String value) {
            addCriterion("A_Title like", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleNotLike(String value) {
            addCriterion("A_Title not like", value, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleIn(List<String> values) {
            addCriterion("A_Title in", values, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleNotIn(List<String> values) {
            addCriterion("A_Title not in", values, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleBetween(String value1, String value2) {
            addCriterion("A_Title between", value1, value2, "aTitle");
            return (Criteria) this;
        }

        public Criteria andATitleNotBetween(String value1, String value2) {
            addCriterion("A_Title not between", value1, value2, "aTitle");
            return (Criteria) this;
        }

        public Criteria andAViewcountIsNull() {
            addCriterion("A_ViewCount is null");
            return (Criteria) this;
        }

        public Criteria andAViewcountIsNotNull() {
            addCriterion("A_ViewCount is not null");
            return (Criteria) this;
        }

        public Criteria andAViewcountEqualTo(Integer value) {
            addCriterion("A_ViewCount =", value, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAViewcountNotEqualTo(Integer value) {
            addCriterion("A_ViewCount <>", value, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAViewcountGreaterThan(Integer value) {
            addCriterion("A_ViewCount >", value, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAViewcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("A_ViewCount >=", value, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAViewcountLessThan(Integer value) {
            addCriterion("A_ViewCount <", value, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAViewcountLessThanOrEqualTo(Integer value) {
            addCriterion("A_ViewCount <=", value, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAViewcountIn(List<Integer> values) {
            addCriterion("A_ViewCount in", values, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAViewcountNotIn(List<Integer> values) {
            addCriterion("A_ViewCount not in", values, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAViewcountBetween(Integer value1, Integer value2) {
            addCriterion("A_ViewCount between", value1, value2, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAViewcountNotBetween(Integer value1, Integer value2) {
            addCriterion("A_ViewCount not between", value1, value2, "aViewcount");
            return (Criteria) this;
        }

        public Criteria andAPraiseIsNull() {
            addCriterion("A_Praise is null");
            return (Criteria) this;
        }

        public Criteria andAPraiseIsNotNull() {
            addCriterion("A_Praise is not null");
            return (Criteria) this;
        }

        public Criteria andAPraiseEqualTo(Integer value) {
            addCriterion("A_Praise =", value, "aPraise");
            return (Criteria) this;
        }

        public Criteria andAPraiseNotEqualTo(Integer value) {
            addCriterion("A_Praise <>", value, "aPraise");
            return (Criteria) this;
        }

        public Criteria andAPraiseGreaterThan(Integer value) {
            addCriterion("A_Praise >", value, "aPraise");
            return (Criteria) this;
        }

        public Criteria andAPraiseGreaterThanOrEqualTo(Integer value) {
            addCriterion("A_Praise >=", value, "aPraise");
            return (Criteria) this;
        }

        public Criteria andAPraiseLessThan(Integer value) {
            addCriterion("A_Praise <", value, "aPraise");
            return (Criteria) this;
        }

        public Criteria andAPraiseLessThanOrEqualTo(Integer value) {
            addCriterion("A_Praise <=", value, "aPraise");
            return (Criteria) this;
        }

        public Criteria andAPraiseIn(List<Integer> values) {
            addCriterion("A_Praise in", values, "aPraise");
            return (Criteria) this;
        }

        public Criteria andAPraiseNotIn(List<Integer> values) {
            addCriterion("A_Praise not in", values, "aPraise");
            return (Criteria) this;
        }

        public Criteria andAPraiseBetween(Integer value1, Integer value2) {
            addCriterion("A_Praise between", value1, value2, "aPraise");
            return (Criteria) this;
        }

        public Criteria andAPraiseNotBetween(Integer value1, Integer value2) {
            addCriterion("A_Praise not between", value1, value2, "aPraise");
            return (Criteria) this;
        }

        public Criteria andATrampleIsNull() {
            addCriterion("A_Trample is null");
            return (Criteria) this;
        }

        public Criteria andATrampleIsNotNull() {
            addCriterion("A_Trample is not null");
            return (Criteria) this;
        }

        public Criteria andATrampleEqualTo(Integer value) {
            addCriterion("A_Trample =", value, "aTrample");
            return (Criteria) this;
        }

        public Criteria andATrampleNotEqualTo(Integer value) {
            addCriterion("A_Trample <>", value, "aTrample");
            return (Criteria) this;
        }

        public Criteria andATrampleGreaterThan(Integer value) {
            addCriterion("A_Trample >", value, "aTrample");
            return (Criteria) this;
        }

        public Criteria andATrampleGreaterThanOrEqualTo(Integer value) {
            addCriterion("A_Trample >=", value, "aTrample");
            return (Criteria) this;
        }

        public Criteria andATrampleLessThan(Integer value) {
            addCriterion("A_Trample <", value, "aTrample");
            return (Criteria) this;
        }

        public Criteria andATrampleLessThanOrEqualTo(Integer value) {
            addCriterion("A_Trample <=", value, "aTrample");
            return (Criteria) this;
        }

        public Criteria andATrampleIn(List<Integer> values) {
            addCriterion("A_Trample in", values, "aTrample");
            return (Criteria) this;
        }

        public Criteria andATrampleNotIn(List<Integer> values) {
            addCriterion("A_Trample not in", values, "aTrample");
            return (Criteria) this;
        }

        public Criteria andATrampleBetween(Integer value1, Integer value2) {
            addCriterion("A_Trample between", value1, value2, "aTrample");
            return (Criteria) this;
        }

        public Criteria andATrampleNotBetween(Integer value1, Integer value2) {
            addCriterion("A_Trample not between", value1, value2, "aTrample");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeIsNull() {
            addCriterion("A_PublishTime is null");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeIsNotNull() {
            addCriterion("A_PublishTime is not null");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeEqualTo(String value) {
            addCriterion("A_PublishTime =", value, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeNotEqualTo(String value) {
            addCriterion("A_PublishTime <>", value, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeGreaterThan(String value) {
            addCriterion("A_PublishTime >", value, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeGreaterThanOrEqualTo(String value) {
            addCriterion("A_PublishTime >=", value, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeLessThan(String value) {
            addCriterion("A_PublishTime <", value, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeLessThanOrEqualTo(String value) {
            addCriterion("A_PublishTime <=", value, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeLike(String value) {
            addCriterion("A_PublishTime like", value, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeNotLike(String value) {
            addCriterion("A_PublishTime not like", value, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeIn(List<String> values) {
            addCriterion("A_PublishTime in", values, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeNotIn(List<String> values) {
            addCriterion("A_PublishTime not in", values, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeBetween(String value1, String value2) {
            addCriterion("A_PublishTime between", value1, value2, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andAPublishtimeNotBetween(String value1, String value2) {
            addCriterion("A_PublishTime not between", value1, value2, "aPublishtime");
            return (Criteria) this;
        }

        public Criteria andACollectedcountIsNull() {
            addCriterion("A_CollectedCount is null");
            return (Criteria) this;
        }

        public Criteria andACollectedcountIsNotNull() {
            addCriterion("A_CollectedCount is not null");
            return (Criteria) this;
        }

        public Criteria andACollectedcountEqualTo(Integer value) {
            addCriterion("A_CollectedCount =", value, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andACollectedcountNotEqualTo(Integer value) {
            addCriterion("A_CollectedCount <>", value, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andACollectedcountGreaterThan(Integer value) {
            addCriterion("A_CollectedCount >", value, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andACollectedcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("A_CollectedCount >=", value, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andACollectedcountLessThan(Integer value) {
            addCriterion("A_CollectedCount <", value, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andACollectedcountLessThanOrEqualTo(Integer value) {
            addCriterion("A_CollectedCount <=", value, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andACollectedcountIn(List<Integer> values) {
            addCriterion("A_CollectedCount in", values, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andACollectedcountNotIn(List<Integer> values) {
            addCriterion("A_CollectedCount not in", values, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andACollectedcountBetween(Integer value1, Integer value2) {
            addCriterion("A_CollectedCount between", value1, value2, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andACollectedcountNotBetween(Integer value1, Integer value2) {
            addCriterion("A_CollectedCount not between", value1, value2, "aCollectedcount");
            return (Criteria) this;
        }

        public Criteria andATypeIsNull() {
            addCriterion("A_Type is null");
            return (Criteria) this;
        }

        public Criteria andATypeIsNotNull() {
            addCriterion("A_Type is not null");
            return (Criteria) this;
        }

        public Criteria andATypeEqualTo(Integer value) {
            addCriterion("A_Type =", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeNotEqualTo(Integer value) {
            addCriterion("A_Type <>", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeGreaterThan(Integer value) {
            addCriterion("A_Type >", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("A_Type >=", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeLessThan(Integer value) {
            addCriterion("A_Type <", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeLessThanOrEqualTo(Integer value) {
            addCriterion("A_Type <=", value, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeIn(List<Integer> values) {
            addCriterion("A_Type in", values, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeNotIn(List<Integer> values) {
            addCriterion("A_Type not in", values, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeBetween(Integer value1, Integer value2) {
            addCriterion("A_Type between", value1, value2, "aType");
            return (Criteria) this;
        }

        public Criteria andATypeNotBetween(Integer value1, Integer value2) {
            addCriterion("A_Type not between", value1, value2, "aType");
            return (Criteria) this;
        }

        public Criteria andAStatusIsNull() {
            addCriterion("A_Status is null");
            return (Criteria) this;
        }

        public Criteria andAStatusIsNotNull() {
            addCriterion("A_Status is not null");
            return (Criteria) this;
        }

        public Criteria andAStatusEqualTo(Integer value) {
            addCriterion("A_Status =", value, "aStatus");
            return (Criteria) this;
        }

        public Criteria andAStatusNotEqualTo(Integer value) {
            addCriterion("A_Status <>", value, "aStatus");
            return (Criteria) this;
        }

        public Criteria andAStatusGreaterThan(Integer value) {
            addCriterion("A_Status >", value, "aStatus");
            return (Criteria) this;
        }

        public Criteria andAStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("A_Status >=", value, "aStatus");
            return (Criteria) this;
        }

        public Criteria andAStatusLessThan(Integer value) {
            addCriterion("A_Status <", value, "aStatus");
            return (Criteria) this;
        }

        public Criteria andAStatusLessThanOrEqualTo(Integer value) {
            addCriterion("A_Status <=", value, "aStatus");
            return (Criteria) this;
        }

        public Criteria andAStatusIn(List<Integer> values) {
            addCriterion("A_Status in", values, "aStatus");
            return (Criteria) this;
        }

        public Criteria andAStatusNotIn(List<Integer> values) {
            addCriterion("A_Status not in", values, "aStatus");
            return (Criteria) this;
        }

        public Criteria andAStatusBetween(Integer value1, Integer value2) {
            addCriterion("A_Status between", value1, value2, "aStatus");
            return (Criteria) this;
        }

        public Criteria andAStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("A_Status not between", value1, value2, "aStatus");
            return (Criteria) this;
        }

        public Criteria andACommentcountIsNull() {
            addCriterion("A_CommentCount is null");
            return (Criteria) this;
        }

        public Criteria andACommentcountIsNotNull() {
            addCriterion("A_CommentCount is not null");
            return (Criteria) this;
        }

        public Criteria andACommentcountEqualTo(Integer value) {
            addCriterion("A_CommentCount =", value, "aCommentcount");
            return (Criteria) this;
        }

        public Criteria andACommentcountNotEqualTo(Integer value) {
            addCriterion("A_CommentCount <>", value, "aCommentcount");
            return (Criteria) this;
        }

        public Criteria andACommentcountGreaterThan(Integer value) {
            addCriterion("A_CommentCount >", value, "aCommentcount");
            return (Criteria) this;
        }

        public Criteria andACommentcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("A_CommentCount >=", value, "aCommentcount");
            return (Criteria) this;
        }

        public Criteria andACommentcountLessThan(Integer value) {
            addCriterion("A_CommentCount <", value, "aCommentcount");
            return (Criteria) this;
        }

        public Criteria andACommentcountLessThanOrEqualTo(Integer value) {
            addCriterion("A_CommentCount <=", value, "aCommentcount");
            return (Criteria) this;
        }

        public Criteria andACommentcountIn(List<Integer> values) {
            addCriterion("A_CommentCount in", values, "aCommentcount");
            return (Criteria) this;
        }

        public Criteria andACommentcountNotIn(List<Integer> values) {
            addCriterion("A_CommentCount not in", values, "aCommentcount");
            return (Criteria) this;
        }

        public Criteria andACommentcountBetween(Integer value1, Integer value2) {
            addCriterion("A_CommentCount between", value1, value2, "aCommentcount");
            return (Criteria) this;
        }

        public Criteria andACommentcountNotBetween(Integer value1, Integer value2) {
            addCriterion("A_CommentCount not between", value1, value2, "aCommentcount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}