package cn.kuqi.Pojo;

public class ArticleClassfiy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_classfiy.AC_Number
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private Integer acNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_classfiy.AC_ClassfiyName
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private String acClassfiyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_classfiy.AC_Remark
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private String acRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_classfiy.AC_Number
     *
     * @return the value of article_classfiy.AC_Number
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public Integer getAcNumber() {
        return acNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_classfiy.AC_Number
     *
     * @param acNumber the value for article_classfiy.AC_Number
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setAcNumber(Integer acNumber) {
        this.acNumber = acNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_classfiy.AC_ClassfiyName
     *
     * @return the value of article_classfiy.AC_ClassfiyName
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getAcClassfiyname() {
        return acClassfiyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_classfiy.AC_ClassfiyName
     *
     * @param acClassfiyname the value for article_classfiy.AC_ClassfiyName
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setAcClassfiyname(String acClassfiyname) {
        this.acClassfiyname = acClassfiyname == null ? null : acClassfiyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_classfiy.AC_Remark
     *
     * @return the value of article_classfiy.AC_Remark
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getAcRemark() {
        return acRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_classfiy.AC_Remark
     *
     * @param acRemark the value for article_classfiy.AC_Remark
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setAcRemark(String acRemark) {
        this.acRemark = acRemark == null ? null : acRemark.trim();
    }
}