package cn.kuqi.Pojo;

import java.util.ArrayList;
import java.util.List;

public class ArticleClassfiyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public ArticleClassfiyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAcNumberIsNull() {
            addCriterion("AC_Number is null");
            return (Criteria) this;
        }

        public Criteria andAcNumberIsNotNull() {
            addCriterion("AC_Number is not null");
            return (Criteria) this;
        }

        public Criteria andAcNumberEqualTo(Integer value) {
            addCriterion("AC_Number =", value, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcNumberNotEqualTo(Integer value) {
            addCriterion("AC_Number <>", value, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcNumberGreaterThan(Integer value) {
            addCriterion("AC_Number >", value, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("AC_Number >=", value, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcNumberLessThan(Integer value) {
            addCriterion("AC_Number <", value, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcNumberLessThanOrEqualTo(Integer value) {
            addCriterion("AC_Number <=", value, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcNumberIn(List<Integer> values) {
            addCriterion("AC_Number in", values, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcNumberNotIn(List<Integer> values) {
            addCriterion("AC_Number not in", values, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcNumberBetween(Integer value1, Integer value2) {
            addCriterion("AC_Number between", value1, value2, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("AC_Number not between", value1, value2, "acNumber");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameIsNull() {
            addCriterion("AC_ClassfiyName is null");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameIsNotNull() {
            addCriterion("AC_ClassfiyName is not null");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameEqualTo(String value) {
            addCriterion("AC_ClassfiyName =", value, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameNotEqualTo(String value) {
            addCriterion("AC_ClassfiyName <>", value, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameGreaterThan(String value) {
            addCriterion("AC_ClassfiyName >", value, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameGreaterThanOrEqualTo(String value) {
            addCriterion("AC_ClassfiyName >=", value, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameLessThan(String value) {
            addCriterion("AC_ClassfiyName <", value, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameLessThanOrEqualTo(String value) {
            addCriterion("AC_ClassfiyName <=", value, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameLike(String value) {
            addCriterion("AC_ClassfiyName like", value, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameNotLike(String value) {
            addCriterion("AC_ClassfiyName not like", value, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameIn(List<String> values) {
            addCriterion("AC_ClassfiyName in", values, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameNotIn(List<String> values) {
            addCriterion("AC_ClassfiyName not in", values, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameBetween(String value1, String value2) {
            addCriterion("AC_ClassfiyName between", value1, value2, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcClassfiynameNotBetween(String value1, String value2) {
            addCriterion("AC_ClassfiyName not between", value1, value2, "acClassfiyname");
            return (Criteria) this;
        }

        public Criteria andAcRemarkIsNull() {
            addCriterion("AC_Remark is null");
            return (Criteria) this;
        }

        public Criteria andAcRemarkIsNotNull() {
            addCriterion("AC_Remark is not null");
            return (Criteria) this;
        }

        public Criteria andAcRemarkEqualTo(String value) {
            addCriterion("AC_Remark =", value, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkNotEqualTo(String value) {
            addCriterion("AC_Remark <>", value, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkGreaterThan(String value) {
            addCriterion("AC_Remark >", value, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("AC_Remark >=", value, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkLessThan(String value) {
            addCriterion("AC_Remark <", value, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkLessThanOrEqualTo(String value) {
            addCriterion("AC_Remark <=", value, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkLike(String value) {
            addCriterion("AC_Remark like", value, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkNotLike(String value) {
            addCriterion("AC_Remark not like", value, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkIn(List<String> values) {
            addCriterion("AC_Remark in", values, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkNotIn(List<String> values) {
            addCriterion("AC_Remark not in", values, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkBetween(String value1, String value2) {
            addCriterion("AC_Remark between", value1, value2, "acRemark");
            return (Criteria) this;
        }

        public Criteria andAcRemarkNotBetween(String value1, String value2) {
            addCriterion("AC_Remark not between", value1, value2, "acRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_classfiy
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}