package cn.kuqi.Pojo;

import java.util.ArrayList;
import java.util.List;

public class ArticleTrampleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public ArticleTrampleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAtNumberIsNull() {
            addCriterion("AT_Number is null");
            return (Criteria) this;
        }

        public Criteria andAtNumberIsNotNull() {
            addCriterion("AT_Number is not null");
            return (Criteria) this;
        }

        public Criteria andAtNumberEqualTo(Integer value) {
            addCriterion("AT_Number =", value, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtNumberNotEqualTo(Integer value) {
            addCriterion("AT_Number <>", value, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtNumberGreaterThan(Integer value) {
            addCriterion("AT_Number >", value, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("AT_Number >=", value, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtNumberLessThan(Integer value) {
            addCriterion("AT_Number <", value, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtNumberLessThanOrEqualTo(Integer value) {
            addCriterion("AT_Number <=", value, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtNumberIn(List<Integer> values) {
            addCriterion("AT_Number in", values, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtNumberNotIn(List<Integer> values) {
            addCriterion("AT_Number not in", values, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtNumberBetween(Integer value1, Integer value2) {
            addCriterion("AT_Number between", value1, value2, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("AT_Number not between", value1, value2, "atNumber");
            return (Criteria) this;
        }

        public Criteria andAtUseridIsNull() {
            addCriterion("AT_UserID is null");
            return (Criteria) this;
        }

        public Criteria andAtUseridIsNotNull() {
            addCriterion("AT_UserID is not null");
            return (Criteria) this;
        }

        public Criteria andAtUseridEqualTo(Integer value) {
            addCriterion("AT_UserID =", value, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtUseridNotEqualTo(Integer value) {
            addCriterion("AT_UserID <>", value, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtUseridGreaterThan(Integer value) {
            addCriterion("AT_UserID >", value, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("AT_UserID >=", value, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtUseridLessThan(Integer value) {
            addCriterion("AT_UserID <", value, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtUseridLessThanOrEqualTo(Integer value) {
            addCriterion("AT_UserID <=", value, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtUseridIn(List<Integer> values) {
            addCriterion("AT_UserID in", values, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtUseridNotIn(List<Integer> values) {
            addCriterion("AT_UserID not in", values, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtUseridBetween(Integer value1, Integer value2) {
            addCriterion("AT_UserID between", value1, value2, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("AT_UserID not between", value1, value2, "atUserid");
            return (Criteria) this;
        }

        public Criteria andAtArticleIsNull() {
            addCriterion("AT_Article is null");
            return (Criteria) this;
        }

        public Criteria andAtArticleIsNotNull() {
            addCriterion("AT_Article is not null");
            return (Criteria) this;
        }

        public Criteria andAtArticleEqualTo(Integer value) {
            addCriterion("AT_Article =", value, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtArticleNotEqualTo(Integer value) {
            addCriterion("AT_Article <>", value, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtArticleGreaterThan(Integer value) {
            addCriterion("AT_Article >", value, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtArticleGreaterThanOrEqualTo(Integer value) {
            addCriterion("AT_Article >=", value, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtArticleLessThan(Integer value) {
            addCriterion("AT_Article <", value, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtArticleLessThanOrEqualTo(Integer value) {
            addCriterion("AT_Article <=", value, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtArticleIn(List<Integer> values) {
            addCriterion("AT_Article in", values, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtArticleNotIn(List<Integer> values) {
            addCriterion("AT_Article not in", values, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtArticleBetween(Integer value1, Integer value2) {
            addCriterion("AT_Article between", value1, value2, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtArticleNotBetween(Integer value1, Integer value2) {
            addCriterion("AT_Article not between", value1, value2, "atArticle");
            return (Criteria) this;
        }

        public Criteria andAtTimeIsNull() {
            addCriterion("AT_Time is null");
            return (Criteria) this;
        }

        public Criteria andAtTimeIsNotNull() {
            addCriterion("AT_Time is not null");
            return (Criteria) this;
        }

        public Criteria andAtTimeEqualTo(String value) {
            addCriterion("AT_Time =", value, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeNotEqualTo(String value) {
            addCriterion("AT_Time <>", value, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeGreaterThan(String value) {
            addCriterion("AT_Time >", value, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeGreaterThanOrEqualTo(String value) {
            addCriterion("AT_Time >=", value, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeLessThan(String value) {
            addCriterion("AT_Time <", value, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeLessThanOrEqualTo(String value) {
            addCriterion("AT_Time <=", value, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeLike(String value) {
            addCriterion("AT_Time like", value, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeNotLike(String value) {
            addCriterion("AT_Time not like", value, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeIn(List<String> values) {
            addCriterion("AT_Time in", values, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeNotIn(List<String> values) {
            addCriterion("AT_Time not in", values, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeBetween(String value1, String value2) {
            addCriterion("AT_Time between", value1, value2, "atTime");
            return (Criteria) this;
        }

        public Criteria andAtTimeNotBetween(String value1, String value2) {
            addCriterion("AT_Time not between", value1, value2, "atTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_trample
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}