package cn.kuqi.Pojo;

public class ArticleTrample {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_trample.AT_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer atNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_trample.AT_UserID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer atUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_trample.AT_Article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer atArticle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_trample.AT_Time
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String atTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_trample.AT_Number
     *
     * @return the value of article_trample.AT_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getAtNumber() {
        return atNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_trample.AT_Number
     *
     * @param atNumber the value for article_trample.AT_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setAtNumber(Integer atNumber) {
        this.atNumber = atNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_trample.AT_UserID
     *
     * @return the value of article_trample.AT_UserID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getAtUserid() {
        return atUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_trample.AT_UserID
     *
     * @param atUserid the value for article_trample.AT_UserID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setAtUserid(Integer atUserid) {
        this.atUserid = atUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_trample.AT_Article
     *
     * @return the value of article_trample.AT_Article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getAtArticle() {
        return atArticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_trample.AT_Article
     *
     * @param atArticle the value for article_trample.AT_Article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setAtArticle(Integer atArticle) {
        this.atArticle = atArticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_trample.AT_Time
     *
     * @return the value of article_trample.AT_Time
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getAtTime() {
        return atTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_trample.AT_Time
     *
     * @param atTime the value for article_trample.AT_Time
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setAtTime(String atTime) {
        this.atTime = atTime == null ? null : atTime.trim();
    }
}