package cn.kuqi.Pojo;

public class ArticlePraise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_praise.AP_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer apNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_praise.AP_UserID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer apUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_praise.AP_Article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer apArticle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_praise.AP_Time
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String apTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_praise.AP_Number
     *
     * @return the value of article_praise.AP_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getApNumber() {
        return apNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_praise.AP_Number
     *
     * @param apNumber the value for article_praise.AP_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setApNumber(Integer apNumber) {
        this.apNumber = apNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_praise.AP_UserID
     *
     * @return the value of article_praise.AP_UserID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getApUserid() {
        return apUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_praise.AP_UserID
     *
     * @param apUserid the value for article_praise.AP_UserID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setApUserid(Integer apUserid) {
        this.apUserid = apUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_praise.AP_Article
     *
     * @return the value of article_praise.AP_Article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getApArticle() {
        return apArticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_praise.AP_Article
     *
     * @param apArticle the value for article_praise.AP_Article
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setApArticle(Integer apArticle) {
        this.apArticle = apArticle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_praise.AP_Time
     *
     * @return the value of article_praise.AP_Time
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getApTime() {
        return apTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_praise.AP_Time
     *
     * @param apTime the value for article_praise.AP_Time
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setApTime(String apTime) {
        this.apTime = apTime == null ? null : apTime.trim();
    }
}