package cn.kuqi.Pojo;

import java.util.ArrayList;
import java.util.List;

public class BloginfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public BloginfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBiNumberIsNull() {
            addCriterion("BI_Number is null");
            return (Criteria) this;
        }

        public Criteria andBiNumberIsNotNull() {
            addCriterion("BI_Number is not null");
            return (Criteria) this;
        }

        public Criteria andBiNumberEqualTo(Integer value) {
            addCriterion("BI_Number =", value, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiNumberNotEqualTo(Integer value) {
            addCriterion("BI_Number <>", value, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiNumberGreaterThan(Integer value) {
            addCriterion("BI_Number >", value, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("BI_Number >=", value, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiNumberLessThan(Integer value) {
            addCriterion("BI_Number <", value, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiNumberLessThanOrEqualTo(Integer value) {
            addCriterion("BI_Number <=", value, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiNumberIn(List<Integer> values) {
            addCriterion("BI_Number in", values, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiNumberNotIn(List<Integer> values) {
            addCriterion("BI_Number not in", values, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiNumberBetween(Integer value1, Integer value2) {
            addCriterion("BI_Number between", value1, value2, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("BI_Number not between", value1, value2, "biNumber");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameIsNull() {
            addCriterion("BI_BlogerNickname is null");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameIsNotNull() {
            addCriterion("BI_BlogerNickname is not null");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameEqualTo(String value) {
            addCriterion("BI_BlogerNickname =", value, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameNotEqualTo(String value) {
            addCriterion("BI_BlogerNickname <>", value, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameGreaterThan(String value) {
            addCriterion("BI_BlogerNickname >", value, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameGreaterThanOrEqualTo(String value) {
            addCriterion("BI_BlogerNickname >=", value, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameLessThan(String value) {
            addCriterion("BI_BlogerNickname <", value, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameLessThanOrEqualTo(String value) {
            addCriterion("BI_BlogerNickname <=", value, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameLike(String value) {
            addCriterion("BI_BlogerNickname like", value, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameNotLike(String value) {
            addCriterion("BI_BlogerNickname not like", value, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameIn(List<String> values) {
            addCriterion("BI_BlogerNickname in", values, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameNotIn(List<String> values) {
            addCriterion("BI_BlogerNickname not in", values, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameBetween(String value1, String value2) {
            addCriterion("BI_BlogerNickname between", value1, value2, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiBlogernicknameNotBetween(String value1, String value2) {
            addCriterion("BI_BlogerNickname not between", value1, value2, "biBlogernickname");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitIsNull() {
            addCriterion("BI_HeadPortrait is null");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitIsNotNull() {
            addCriterion("BI_HeadPortrait is not null");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitEqualTo(String value) {
            addCriterion("BI_HeadPortrait =", value, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitNotEqualTo(String value) {
            addCriterion("BI_HeadPortrait <>", value, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitGreaterThan(String value) {
            addCriterion("BI_HeadPortrait >", value, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitGreaterThanOrEqualTo(String value) {
            addCriterion("BI_HeadPortrait >=", value, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitLessThan(String value) {
            addCriterion("BI_HeadPortrait <", value, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitLessThanOrEqualTo(String value) {
            addCriterion("BI_HeadPortrait <=", value, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitLike(String value) {
            addCriterion("BI_HeadPortrait like", value, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitNotLike(String value) {
            addCriterion("BI_HeadPortrait not like", value, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitIn(List<String> values) {
            addCriterion("BI_HeadPortrait in", values, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitNotIn(List<String> values) {
            addCriterion("BI_HeadPortrait not in", values, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitBetween(String value1, String value2) {
            addCriterion("BI_HeadPortrait between", value1, value2, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiHeadportraitNotBetween(String value1, String value2) {
            addCriterion("BI_HeadPortrait not between", value1, value2, "biHeadportrait");
            return (Criteria) this;
        }

        public Criteria andBiBlognameIsNull() {
            addCriterion("BI_BlogName is null");
            return (Criteria) this;
        }

        public Criteria andBiBlognameIsNotNull() {
            addCriterion("BI_BlogName is not null");
            return (Criteria) this;
        }

        public Criteria andBiBlognameEqualTo(String value) {
            addCriterion("BI_BlogName =", value, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameNotEqualTo(String value) {
            addCriterion("BI_BlogName <>", value, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameGreaterThan(String value) {
            addCriterion("BI_BlogName >", value, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameGreaterThanOrEqualTo(String value) {
            addCriterion("BI_BlogName >=", value, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameLessThan(String value) {
            addCriterion("BI_BlogName <", value, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameLessThanOrEqualTo(String value) {
            addCriterion("BI_BlogName <=", value, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameLike(String value) {
            addCriterion("BI_BlogName like", value, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameNotLike(String value) {
            addCriterion("BI_BlogName not like", value, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameIn(List<String> values) {
            addCriterion("BI_BlogName in", values, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameNotIn(List<String> values) {
            addCriterion("BI_BlogName not in", values, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameBetween(String value1, String value2) {
            addCriterion("BI_BlogName between", value1, value2, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiBlognameNotBetween(String value1, String value2) {
            addCriterion("BI_BlogName not between", value1, value2, "biBlogname");
            return (Criteria) this;
        }

        public Criteria andBiAntistopIsNull() {
            addCriterion("BI_Antistop is null");
            return (Criteria) this;
        }

        public Criteria andBiAntistopIsNotNull() {
            addCriterion("BI_Antistop is not null");
            return (Criteria) this;
        }

        public Criteria andBiAntistopEqualTo(String value) {
            addCriterion("BI_Antistop =", value, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopNotEqualTo(String value) {
            addCriterion("BI_Antistop <>", value, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopGreaterThan(String value) {
            addCriterion("BI_Antistop >", value, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopGreaterThanOrEqualTo(String value) {
            addCriterion("BI_Antistop >=", value, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopLessThan(String value) {
            addCriterion("BI_Antistop <", value, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopLessThanOrEqualTo(String value) {
            addCriterion("BI_Antistop <=", value, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopLike(String value) {
            addCriterion("BI_Antistop like", value, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopNotLike(String value) {
            addCriterion("BI_Antistop not like", value, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopIn(List<String> values) {
            addCriterion("BI_Antistop in", values, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopNotIn(List<String> values) {
            addCriterion("BI_Antistop not in", values, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopBetween(String value1, String value2) {
            addCriterion("BI_Antistop between", value1, value2, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiAntistopNotBetween(String value1, String value2) {
            addCriterion("BI_Antistop not between", value1, value2, "biAntistop");
            return (Criteria) this;
        }

        public Criteria andBiMottoIsNull() {
            addCriterion("BI_Motto is null");
            return (Criteria) this;
        }

        public Criteria andBiMottoIsNotNull() {
            addCriterion("BI_Motto is not null");
            return (Criteria) this;
        }

        public Criteria andBiMottoEqualTo(String value) {
            addCriterion("BI_Motto =", value, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoNotEqualTo(String value) {
            addCriterion("BI_Motto <>", value, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoGreaterThan(String value) {
            addCriterion("BI_Motto >", value, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoGreaterThanOrEqualTo(String value) {
            addCriterion("BI_Motto >=", value, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoLessThan(String value) {
            addCriterion("BI_Motto <", value, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoLessThanOrEqualTo(String value) {
            addCriterion("BI_Motto <=", value, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoLike(String value) {
            addCriterion("BI_Motto like", value, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoNotLike(String value) {
            addCriterion("BI_Motto not like", value, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoIn(List<String> values) {
            addCriterion("BI_Motto in", values, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoNotIn(List<String> values) {
            addCriterion("BI_Motto not in", values, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoBetween(String value1, String value2) {
            addCriterion("BI_Motto between", value1, value2, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiMottoNotBetween(String value1, String value2) {
            addCriterion("BI_Motto not between", value1, value2, "biMotto");
            return (Criteria) this;
        }

        public Criteria andBiThemeIsNull() {
            addCriterion("BI_Theme is null");
            return (Criteria) this;
        }

        public Criteria andBiThemeIsNotNull() {
            addCriterion("BI_Theme is not null");
            return (Criteria) this;
        }

        public Criteria andBiThemeEqualTo(Integer value) {
            addCriterion("BI_Theme =", value, "biTheme");
            return (Criteria) this;
        }

        public Criteria andBiThemeNotEqualTo(Integer value) {
            addCriterion("BI_Theme <>", value, "biTheme");
            return (Criteria) this;
        }

        public Criteria andBiThemeGreaterThan(Integer value) {
            addCriterion("BI_Theme >", value, "biTheme");
            return (Criteria) this;
        }

        public Criteria andBiThemeGreaterThanOrEqualTo(Integer value) {
            addCriterion("BI_Theme >=", value, "biTheme");
            return (Criteria) this;
        }

        public Criteria andBiThemeLessThan(Integer value) {
            addCriterion("BI_Theme <", value, "biTheme");
            return (Criteria) this;
        }

        public Criteria andBiThemeLessThanOrEqualTo(Integer value) {
            addCriterion("BI_Theme <=", value, "biTheme");
            return (Criteria) this;
        }

        public Criteria andBiThemeIn(List<Integer> values) {
            addCriterion("BI_Theme in", values, "biTheme");
            return (Criteria) this;
        }

        public Criteria andBiThemeNotIn(List<Integer> values) {
            addCriterion("BI_Theme not in", values, "biTheme");
            return (Criteria) this;
        }

        public Criteria andBiThemeBetween(Integer value1, Integer value2) {
            addCriterion("BI_Theme between", value1, value2, "biTheme");
            return (Criteria) this;
        }

        public Criteria andBiThemeNotBetween(Integer value1, Integer value2) {
            addCriterion("BI_Theme not between", value1, value2, "biTheme");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bloginfo
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bloginfo
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}