package cn.kuqi.Pojo;

public class Bloginfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloginfo.BI_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer biNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloginfo.BI_BlogerNickname
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String biBlogernickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloginfo.BI_HeadPortrait
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String biHeadportrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloginfo.BI_BlogName
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String biBlogname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloginfo.BI_Antistop
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String biAntistop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloginfo.BI_Motto
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String biMotto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bloginfo.BI_Theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer biTheme;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloginfo.BI_Number
     *
     * @return the value of bloginfo.BI_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getBiNumber() {
        return biNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloginfo.BI_Number
     *
     * @param biNumber the value for bloginfo.BI_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setBiNumber(Integer biNumber) {
        this.biNumber = biNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloginfo.BI_BlogerNickname
     *
     * @return the value of bloginfo.BI_BlogerNickname
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getBiBlogernickname() {
        return biBlogernickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloginfo.BI_BlogerNickname
     *
     * @param biBlogernickname the value for bloginfo.BI_BlogerNickname
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setBiBlogernickname(String biBlogernickname) {
        this.biBlogernickname = biBlogernickname == null ? null : biBlogernickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloginfo.BI_HeadPortrait
     *
     * @return the value of bloginfo.BI_HeadPortrait
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getBiHeadportrait() {
        return biHeadportrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloginfo.BI_HeadPortrait
     *
     * @param biHeadportrait the value for bloginfo.BI_HeadPortrait
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setBiHeadportrait(String biHeadportrait) {
        this.biHeadportrait = biHeadportrait == null ? null : biHeadportrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloginfo.BI_BlogName
     *
     * @return the value of bloginfo.BI_BlogName
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getBiBlogname() {
        return biBlogname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloginfo.BI_BlogName
     *
     * @param biBlogname the value for bloginfo.BI_BlogName
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setBiBlogname(String biBlogname) {
        this.biBlogname = biBlogname == null ? null : biBlogname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloginfo.BI_Antistop
     *
     * @return the value of bloginfo.BI_Antistop
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getBiAntistop() {
        return biAntistop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloginfo.BI_Antistop
     *
     * @param biAntistop the value for bloginfo.BI_Antistop
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setBiAntistop(String biAntistop) {
        this.biAntistop = biAntistop == null ? null : biAntistop.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloginfo.BI_Motto
     *
     * @return the value of bloginfo.BI_Motto
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getBiMotto() {
        return biMotto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloginfo.BI_Motto
     *
     * @param biMotto the value for bloginfo.BI_Motto
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setBiMotto(String biMotto) {
        this.biMotto = biMotto == null ? null : biMotto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bloginfo.BI_Theme
     *
     * @return the value of bloginfo.BI_Theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getBiTheme() {
        return biTheme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bloginfo.BI_Theme
     *
     * @param biTheme the value for bloginfo.BI_Theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setBiTheme(Integer biTheme) {
        this.biTheme = biTheme;
    }
}