package cn.kuqi.Pojo;

public class Link {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.L_Number
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    private Integer lNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.L_Name
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    private String lName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.L_AddTime
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    private String lAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.L_ClickCount
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    private Integer lClickcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.L_Link
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    private String lLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link.L_Show
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    private Integer lShow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.L_Number
     *
     * @return the value of link.L_Number
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public Integer getlNumber() {
        return lNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.L_Number
     *
     * @param lNumber the value for link.L_Number
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public void setlNumber(Integer lNumber) {
        this.lNumber = lNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.L_Name
     *
     * @return the value of link.L_Name
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public String getlName() {
        return lName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.L_Name
     *
     * @param lName the value for link.L_Name
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public void setlName(String lName) {
        this.lName = lName == null ? null : lName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.L_AddTime
     *
     * @return the value of link.L_AddTime
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public String getlAddtime() {
        return lAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.L_AddTime
     *
     * @param lAddtime the value for link.L_AddTime
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public void setlAddtime(String lAddtime) {
        this.lAddtime = lAddtime == null ? null : lAddtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.L_ClickCount
     *
     * @return the value of link.L_ClickCount
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public Integer getlClickcount() {
        return lClickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.L_ClickCount
     *
     * @param lClickcount the value for link.L_ClickCount
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public void setlClickcount(Integer lClickcount) {
        this.lClickcount = lClickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.L_Link
     *
     * @return the value of link.L_Link
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public String getlLink() {
        return lLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.L_Link
     *
     * @param lLink the value for link.L_Link
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public void setlLink(String lLink) {
        this.lLink = lLink == null ? null : lLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link.L_Show
     *
     * @return the value of link.L_Show
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public Integer getlShow() {
        return lShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link.L_Show
     *
     * @param lShow the value for link.L_Show
     *
     * @mbg.generated Wed Jan 16 15:43:06 CST 2019
     */
    public void setlShow(Integer lShow) {
        this.lShow = lShow;
    }
}