package cn.kuqi.Pojo;

import java.util.ArrayList;
import java.util.List;

public class ThemeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public ThemeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTNumberIsNull() {
            addCriterion("T_Number is null");
            return (Criteria) this;
        }

        public Criteria andTNumberIsNotNull() {
            addCriterion("T_Number is not null");
            return (Criteria) this;
        }

        public Criteria andTNumberEqualTo(Integer value) {
            addCriterion("T_Number =", value, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTNumberNotEqualTo(Integer value) {
            addCriterion("T_Number <>", value, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTNumberGreaterThan(Integer value) {
            addCriterion("T_Number >", value, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("T_Number >=", value, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTNumberLessThan(Integer value) {
            addCriterion("T_Number <", value, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTNumberLessThanOrEqualTo(Integer value) {
            addCriterion("T_Number <=", value, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTNumberIn(List<Integer> values) {
            addCriterion("T_Number in", values, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTNumberNotIn(List<Integer> values) {
            addCriterion("T_Number not in", values, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTNumberBetween(Integer value1, Integer value2) {
            addCriterion("T_Number between", value1, value2, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("T_Number not between", value1, value2, "tNumber");
            return (Criteria) this;
        }

        public Criteria andTTitleIsNull() {
            addCriterion("T_Title is null");
            return (Criteria) this;
        }

        public Criteria andTTitleIsNotNull() {
            addCriterion("T_Title is not null");
            return (Criteria) this;
        }

        public Criteria andTTitleEqualTo(String value) {
            addCriterion("T_Title =", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleNotEqualTo(String value) {
            addCriterion("T_Title <>", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleGreaterThan(String value) {
            addCriterion("T_Title >", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleGreaterThanOrEqualTo(String value) {
            addCriterion("T_Title >=", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleLessThan(String value) {
            addCriterion("T_Title <", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleLessThanOrEqualTo(String value) {
            addCriterion("T_Title <=", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleLike(String value) {
            addCriterion("T_Title like", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleNotLike(String value) {
            addCriterion("T_Title not like", value, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleIn(List<String> values) {
            addCriterion("T_Title in", values, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleNotIn(List<String> values) {
            addCriterion("T_Title not in", values, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleBetween(String value1, String value2) {
            addCriterion("T_Title between", value1, value2, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTTitleNotBetween(String value1, String value2) {
            addCriterion("T_Title not between", value1, value2, "tTitle");
            return (Criteria) this;
        }

        public Criteria andTUrlIsNull() {
            addCriterion("T_Url is null");
            return (Criteria) this;
        }

        public Criteria andTUrlIsNotNull() {
            addCriterion("T_Url is not null");
            return (Criteria) this;
        }

        public Criteria andTUrlEqualTo(String value) {
            addCriterion("T_Url =", value, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlNotEqualTo(String value) {
            addCriterion("T_Url <>", value, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlGreaterThan(String value) {
            addCriterion("T_Url >", value, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlGreaterThanOrEqualTo(String value) {
            addCriterion("T_Url >=", value, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlLessThan(String value) {
            addCriterion("T_Url <", value, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlLessThanOrEqualTo(String value) {
            addCriterion("T_Url <=", value, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlLike(String value) {
            addCriterion("T_Url like", value, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlNotLike(String value) {
            addCriterion("T_Url not like", value, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlIn(List<String> values) {
            addCriterion("T_Url in", values, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlNotIn(List<String> values) {
            addCriterion("T_Url not in", values, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlBetween(String value1, String value2) {
            addCriterion("T_Url between", value1, value2, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUrlNotBetween(String value1, String value2) {
            addCriterion("T_Url not between", value1, value2, "tUrl");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeIsNull() {
            addCriterion("T_UploadTime is null");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeIsNotNull() {
            addCriterion("T_UploadTime is not null");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeEqualTo(String value) {
            addCriterion("T_UploadTime =", value, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeNotEqualTo(String value) {
            addCriterion("T_UploadTime <>", value, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeGreaterThan(String value) {
            addCriterion("T_UploadTime >", value, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeGreaterThanOrEqualTo(String value) {
            addCriterion("T_UploadTime >=", value, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeLessThan(String value) {
            addCriterion("T_UploadTime <", value, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeLessThanOrEqualTo(String value) {
            addCriterion("T_UploadTime <=", value, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeLike(String value) {
            addCriterion("T_UploadTime like", value, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeNotLike(String value) {
            addCriterion("T_UploadTime not like", value, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeIn(List<String> values) {
            addCriterion("T_UploadTime in", values, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeNotIn(List<String> values) {
            addCriterion("T_UploadTime not in", values, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeBetween(String value1, String value2) {
            addCriterion("T_UploadTime between", value1, value2, "tUploadtime");
            return (Criteria) this;
        }

        public Criteria andTUploadtimeNotBetween(String value1, String value2) {
            addCriterion("T_UploadTime not between", value1, value2, "tUploadtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theme
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theme
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}