package cn.kuqi.Pojo;

public class TimeUserlogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_userlogin.UL_Number
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private Integer ulNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_userlogin.UL_ID
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private Integer ulId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_userlogin.UL_Time
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private String ulTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_userlogin.UL_Number
     *
     * @return the value of time_userlogin.UL_Number
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public Integer getUlNumber() {
        return ulNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_userlogin.UL_Number
     *
     * @param ulNumber the value for time_userlogin.UL_Number
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setUlNumber(Integer ulNumber) {
        this.ulNumber = ulNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_userlogin.UL_ID
     *
     * @return the value of time_userlogin.UL_ID
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public Integer getUlId() {
        return ulId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_userlogin.UL_ID
     *
     * @param ulId the value for time_userlogin.UL_ID
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setUlId(Integer ulId) {
        this.ulId = ulId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_userlogin.UL_Time
     *
     * @return the value of time_userlogin.UL_Time
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getUlTime() {
        return ulTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_userlogin.UL_Time
     *
     * @param ulTime the value for time_userlogin.UL_Time
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setUlTime(String ulTime) {
        this.ulTime = ulTime == null ? null : ulTime.trim();
    }
}