package cn.kuqi.Pojo;

import java.util.ArrayList;
import java.util.List;

public class TimeUserloginExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public TimeUserloginExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUlNumberIsNull() {
            addCriterion("UL_Number is null");
            return (Criteria) this;
        }

        public Criteria andUlNumberIsNotNull() {
            addCriterion("UL_Number is not null");
            return (Criteria) this;
        }

        public Criteria andUlNumberEqualTo(Integer value) {
            addCriterion("UL_Number =", value, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlNumberNotEqualTo(Integer value) {
            addCriterion("UL_Number <>", value, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlNumberGreaterThan(Integer value) {
            addCriterion("UL_Number >", value, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("UL_Number >=", value, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlNumberLessThan(Integer value) {
            addCriterion("UL_Number <", value, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlNumberLessThanOrEqualTo(Integer value) {
            addCriterion("UL_Number <=", value, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlNumberIn(List<Integer> values) {
            addCriterion("UL_Number in", values, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlNumberNotIn(List<Integer> values) {
            addCriterion("UL_Number not in", values, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlNumberBetween(Integer value1, Integer value2) {
            addCriterion("UL_Number between", value1, value2, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("UL_Number not between", value1, value2, "ulNumber");
            return (Criteria) this;
        }

        public Criteria andUlIdIsNull() {
            addCriterion("UL_ID is null");
            return (Criteria) this;
        }

        public Criteria andUlIdIsNotNull() {
            addCriterion("UL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUlIdEqualTo(Integer value) {
            addCriterion("UL_ID =", value, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlIdNotEqualTo(Integer value) {
            addCriterion("UL_ID <>", value, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlIdGreaterThan(Integer value) {
            addCriterion("UL_ID >", value, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("UL_ID >=", value, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlIdLessThan(Integer value) {
            addCriterion("UL_ID <", value, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlIdLessThanOrEqualTo(Integer value) {
            addCriterion("UL_ID <=", value, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlIdIn(List<Integer> values) {
            addCriterion("UL_ID in", values, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlIdNotIn(List<Integer> values) {
            addCriterion("UL_ID not in", values, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlIdBetween(Integer value1, Integer value2) {
            addCriterion("UL_ID between", value1, value2, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlIdNotBetween(Integer value1, Integer value2) {
            addCriterion("UL_ID not between", value1, value2, "ulId");
            return (Criteria) this;
        }

        public Criteria andUlTimeIsNull() {
            addCriterion("UL_Time is null");
            return (Criteria) this;
        }

        public Criteria andUlTimeIsNotNull() {
            addCriterion("UL_Time is not null");
            return (Criteria) this;
        }

        public Criteria andUlTimeEqualTo(String value) {
            addCriterion("UL_Time =", value, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeNotEqualTo(String value) {
            addCriterion("UL_Time <>", value, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeGreaterThan(String value) {
            addCriterion("UL_Time >", value, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeGreaterThanOrEqualTo(String value) {
            addCriterion("UL_Time >=", value, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeLessThan(String value) {
            addCriterion("UL_Time <", value, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeLessThanOrEqualTo(String value) {
            addCriterion("UL_Time <=", value, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeLike(String value) {
            addCriterion("UL_Time like", value, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeNotLike(String value) {
            addCriterion("UL_Time not like", value, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeIn(List<String> values) {
            addCriterion("UL_Time in", values, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeNotIn(List<String> values) {
            addCriterion("UL_Time not in", values, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeBetween(String value1, String value2) {
            addCriterion("UL_Time between", value1, value2, "ulTime");
            return (Criteria) this;
        }

        public Criteria andUlTimeNotBetween(String value1, String value2) {
            addCriterion("UL_Time not between", value1, value2, "ulTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table time_userlogin
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}