package cn.kuqi.Pojo;

public class UserComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.UC_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer ucNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.UC_ID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer ucId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.UC_CommentNumber
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer ucCommentnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.UC_Tier
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer ucTier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.UC_Content
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String ucContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.UC_Praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer ucPraise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.UC_Trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private Integer ucTrample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_comment.UC_PublishTime
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    private String ucPublishtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.UC_Number
     *
     * @return the value of user_comment.UC_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getUcNumber() {
        return ucNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.UC_Number
     *
     * @param ucNumber the value for user_comment.UC_Number
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setUcNumber(Integer ucNumber) {
        this.ucNumber = ucNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.UC_ID
     *
     * @return the value of user_comment.UC_ID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getUcId() {
        return ucId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.UC_ID
     *
     * @param ucId the value for user_comment.UC_ID
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setUcId(Integer ucId) {
        this.ucId = ucId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.UC_CommentNumber
     *
     * @return the value of user_comment.UC_CommentNumber
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getUcCommentnumber() {
        return ucCommentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.UC_CommentNumber
     *
     * @param ucCommentnumber the value for user_comment.UC_CommentNumber
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setUcCommentnumber(Integer ucCommentnumber) {
        this.ucCommentnumber = ucCommentnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.UC_Tier
     *
     * @return the value of user_comment.UC_Tier
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getUcTier() {
        return ucTier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.UC_Tier
     *
     * @param ucTier the value for user_comment.UC_Tier
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setUcTier(Integer ucTier) {
        this.ucTier = ucTier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.UC_Content
     *
     * @return the value of user_comment.UC_Content
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getUcContent() {
        return ucContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.UC_Content
     *
     * @param ucContent the value for user_comment.UC_Content
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setUcContent(String ucContent) {
        this.ucContent = ucContent == null ? null : ucContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.UC_Praise
     *
     * @return the value of user_comment.UC_Praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getUcPraise() {
        return ucPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.UC_Praise
     *
     * @param ucPraise the value for user_comment.UC_Praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setUcPraise(Integer ucPraise) {
        this.ucPraise = ucPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.UC_Trample
     *
     * @return the value of user_comment.UC_Trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Integer getUcTrample() {
        return ucTrample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.UC_Trample
     *
     * @param ucTrample the value for user_comment.UC_Trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setUcTrample(Integer ucTrample) {
        this.ucTrample = ucTrample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_comment.UC_PublishTime
     *
     * @return the value of user_comment.UC_PublishTime
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getUcPublishtime() {
        return ucPublishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_comment.UC_PublishTime
     *
     * @param ucPublishtime the value for user_comment.UC_PublishTime
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setUcPublishtime(String ucPublishtime) {
        this.ucPublishtime = ucPublishtime == null ? null : ucPublishtime.trim();
    }
}