package cn.kuqi.Pojo;

import java.util.ArrayList;
import java.util.List;

public class UserCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public UserCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUcNumberIsNull() {
            addCriterion("UC_Number is null");
            return (Criteria) this;
        }

        public Criteria andUcNumberIsNotNull() {
            addCriterion("UC_Number is not null");
            return (Criteria) this;
        }

        public Criteria andUcNumberEqualTo(Integer value) {
            addCriterion("UC_Number =", value, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcNumberNotEqualTo(Integer value) {
            addCriterion("UC_Number <>", value, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcNumberGreaterThan(Integer value) {
            addCriterion("UC_Number >", value, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("UC_Number >=", value, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcNumberLessThan(Integer value) {
            addCriterion("UC_Number <", value, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcNumberLessThanOrEqualTo(Integer value) {
            addCriterion("UC_Number <=", value, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcNumberIn(List<Integer> values) {
            addCriterion("UC_Number in", values, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcNumberNotIn(List<Integer> values) {
            addCriterion("UC_Number not in", values, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcNumberBetween(Integer value1, Integer value2) {
            addCriterion("UC_Number between", value1, value2, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("UC_Number not between", value1, value2, "ucNumber");
            return (Criteria) this;
        }

        public Criteria andUcIdIsNull() {
            addCriterion("UC_ID is null");
            return (Criteria) this;
        }

        public Criteria andUcIdIsNotNull() {
            addCriterion("UC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUcIdEqualTo(Integer value) {
            addCriterion("UC_ID =", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdNotEqualTo(Integer value) {
            addCriterion("UC_ID <>", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdGreaterThan(Integer value) {
            addCriterion("UC_ID >", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("UC_ID >=", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdLessThan(Integer value) {
            addCriterion("UC_ID <", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdLessThanOrEqualTo(Integer value) {
            addCriterion("UC_ID <=", value, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdIn(List<Integer> values) {
            addCriterion("UC_ID in", values, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdNotIn(List<Integer> values) {
            addCriterion("UC_ID not in", values, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdBetween(Integer value1, Integer value2) {
            addCriterion("UC_ID between", value1, value2, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcIdNotBetween(Integer value1, Integer value2) {
            addCriterion("UC_ID not between", value1, value2, "ucId");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberIsNull() {
            addCriterion("UC_CommentNumber is null");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberIsNotNull() {
            addCriterion("UC_CommentNumber is not null");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberEqualTo(Integer value) {
            addCriterion("UC_CommentNumber =", value, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberNotEqualTo(Integer value) {
            addCriterion("UC_CommentNumber <>", value, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberGreaterThan(Integer value) {
            addCriterion("UC_CommentNumber >", value, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("UC_CommentNumber >=", value, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberLessThan(Integer value) {
            addCriterion("UC_CommentNumber <", value, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberLessThanOrEqualTo(Integer value) {
            addCriterion("UC_CommentNumber <=", value, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberIn(List<Integer> values) {
            addCriterion("UC_CommentNumber in", values, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberNotIn(List<Integer> values) {
            addCriterion("UC_CommentNumber not in", values, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberBetween(Integer value1, Integer value2) {
            addCriterion("UC_CommentNumber between", value1, value2, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcCommentnumberNotBetween(Integer value1, Integer value2) {
            addCriterion("UC_CommentNumber not between", value1, value2, "ucCommentnumber");
            return (Criteria) this;
        }

        public Criteria andUcTierIsNull() {
            addCriterion("UC_Tier is null");
            return (Criteria) this;
        }

        public Criteria andUcTierIsNotNull() {
            addCriterion("UC_Tier is not null");
            return (Criteria) this;
        }

        public Criteria andUcTierEqualTo(Integer value) {
            addCriterion("UC_Tier =", value, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcTierNotEqualTo(Integer value) {
            addCriterion("UC_Tier <>", value, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcTierGreaterThan(Integer value) {
            addCriterion("UC_Tier >", value, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcTierGreaterThanOrEqualTo(Integer value) {
            addCriterion("UC_Tier >=", value, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcTierLessThan(Integer value) {
            addCriterion("UC_Tier <", value, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcTierLessThanOrEqualTo(Integer value) {
            addCriterion("UC_Tier <=", value, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcTierIn(List<Integer> values) {
            addCriterion("UC_Tier in", values, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcTierNotIn(List<Integer> values) {
            addCriterion("UC_Tier not in", values, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcTierBetween(Integer value1, Integer value2) {
            addCriterion("UC_Tier between", value1, value2, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcTierNotBetween(Integer value1, Integer value2) {
            addCriterion("UC_Tier not between", value1, value2, "ucTier");
            return (Criteria) this;
        }

        public Criteria andUcContentIsNull() {
            addCriterion("UC_Content is null");
            return (Criteria) this;
        }

        public Criteria andUcContentIsNotNull() {
            addCriterion("UC_Content is not null");
            return (Criteria) this;
        }

        public Criteria andUcContentEqualTo(String value) {
            addCriterion("UC_Content =", value, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentNotEqualTo(String value) {
            addCriterion("UC_Content <>", value, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentGreaterThan(String value) {
            addCriterion("UC_Content >", value, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentGreaterThanOrEqualTo(String value) {
            addCriterion("UC_Content >=", value, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentLessThan(String value) {
            addCriterion("UC_Content <", value, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentLessThanOrEqualTo(String value) {
            addCriterion("UC_Content <=", value, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentLike(String value) {
            addCriterion("UC_Content like", value, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentNotLike(String value) {
            addCriterion("UC_Content not like", value, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentIn(List<String> values) {
            addCriterion("UC_Content in", values, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentNotIn(List<String> values) {
            addCriterion("UC_Content not in", values, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentBetween(String value1, String value2) {
            addCriterion("UC_Content between", value1, value2, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcContentNotBetween(String value1, String value2) {
            addCriterion("UC_Content not between", value1, value2, "ucContent");
            return (Criteria) this;
        }

        public Criteria andUcPraiseIsNull() {
            addCriterion("UC_Praise is null");
            return (Criteria) this;
        }

        public Criteria andUcPraiseIsNotNull() {
            addCriterion("UC_Praise is not null");
            return (Criteria) this;
        }

        public Criteria andUcPraiseEqualTo(Integer value) {
            addCriterion("UC_Praise =", value, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcPraiseNotEqualTo(Integer value) {
            addCriterion("UC_Praise <>", value, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcPraiseGreaterThan(Integer value) {
            addCriterion("UC_Praise >", value, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcPraiseGreaterThanOrEqualTo(Integer value) {
            addCriterion("UC_Praise >=", value, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcPraiseLessThan(Integer value) {
            addCriterion("UC_Praise <", value, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcPraiseLessThanOrEqualTo(Integer value) {
            addCriterion("UC_Praise <=", value, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcPraiseIn(List<Integer> values) {
            addCriterion("UC_Praise in", values, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcPraiseNotIn(List<Integer> values) {
            addCriterion("UC_Praise not in", values, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcPraiseBetween(Integer value1, Integer value2) {
            addCriterion("UC_Praise between", value1, value2, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcPraiseNotBetween(Integer value1, Integer value2) {
            addCriterion("UC_Praise not between", value1, value2, "ucPraise");
            return (Criteria) this;
        }

        public Criteria andUcTrampleIsNull() {
            addCriterion("UC_Trample is null");
            return (Criteria) this;
        }

        public Criteria andUcTrampleIsNotNull() {
            addCriterion("UC_Trample is not null");
            return (Criteria) this;
        }

        public Criteria andUcTrampleEqualTo(Integer value) {
            addCriterion("UC_Trample =", value, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcTrampleNotEqualTo(Integer value) {
            addCriterion("UC_Trample <>", value, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcTrampleGreaterThan(Integer value) {
            addCriterion("UC_Trample >", value, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcTrampleGreaterThanOrEqualTo(Integer value) {
            addCriterion("UC_Trample >=", value, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcTrampleLessThan(Integer value) {
            addCriterion("UC_Trample <", value, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcTrampleLessThanOrEqualTo(Integer value) {
            addCriterion("UC_Trample <=", value, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcTrampleIn(List<Integer> values) {
            addCriterion("UC_Trample in", values, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcTrampleNotIn(List<Integer> values) {
            addCriterion("UC_Trample not in", values, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcTrampleBetween(Integer value1, Integer value2) {
            addCriterion("UC_Trample between", value1, value2, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcTrampleNotBetween(Integer value1, Integer value2) {
            addCriterion("UC_Trample not between", value1, value2, "ucTrample");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeIsNull() {
            addCriterion("UC_PublishTime is null");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeIsNotNull() {
            addCriterion("UC_PublishTime is not null");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeEqualTo(String value) {
            addCriterion("UC_PublishTime =", value, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeNotEqualTo(String value) {
            addCriterion("UC_PublishTime <>", value, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeGreaterThan(String value) {
            addCriterion("UC_PublishTime >", value, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeGreaterThanOrEqualTo(String value) {
            addCriterion("UC_PublishTime >=", value, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeLessThan(String value) {
            addCriterion("UC_PublishTime <", value, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeLessThanOrEqualTo(String value) {
            addCriterion("UC_PublishTime <=", value, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeLike(String value) {
            addCriterion("UC_PublishTime like", value, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeNotLike(String value) {
            addCriterion("UC_PublishTime not like", value, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeIn(List<String> values) {
            addCriterion("UC_PublishTime in", values, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeNotIn(List<String> values) {
            addCriterion("UC_PublishTime not in", values, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeBetween(String value1, String value2) {
            addCriterion("UC_PublishTime between", value1, value2, "ucPublishtime");
            return (Criteria) this;
        }

        public Criteria andUcPublishtimeNotBetween(String value1, String value2) {
            addCriterion("UC_PublishTime not between", value1, value2, "ucPublishtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_comment
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 11 14:40:37 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_comment
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}