package cn.kuqi.Pojo;

public class Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.U_ID
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private Integer uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.U_Name
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private String uName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.U_Nickname
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private String uNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.U_Signature
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private String uSignature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.U_Email
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private String uEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.U_Psw
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private String uPsw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.U_RegisterTime
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private String uRegistertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.U_Permission
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    private Integer uPermission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.U_ID
     *
     * @return the value of users.U_ID
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.U_ID
     *
     * @param uId the value for users.U_ID
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.U_Name
     *
     * @return the value of users.U_Name
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.U_Name
     *
     * @param uName the value for users.U_Name
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.U_Nickname
     *
     * @return the value of users.U_Nickname
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getuNickname() {
        return uNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.U_Nickname
     *
     * @param uNickname the value for users.U_Nickname
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setuNickname(String uNickname) {
        this.uNickname = uNickname == null ? null : uNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.U_Signature
     *
     * @return the value of users.U_Signature
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getuSignature() {
        return uSignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.U_Signature
     *
     * @param uSignature the value for users.U_Signature
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setuSignature(String uSignature) {
        this.uSignature = uSignature == null ? null : uSignature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.U_Email
     *
     * @return the value of users.U_Email
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getuEmail() {
        return uEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.U_Email
     *
     * @param uEmail the value for users.U_Email
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setuEmail(String uEmail) {
        this.uEmail = uEmail == null ? null : uEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.U_Psw
     *
     * @return the value of users.U_Psw
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getuPsw() {
        return uPsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.U_Psw
     *
     * @param uPsw the value for users.U_Psw
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setuPsw(String uPsw) {
        this.uPsw = uPsw == null ? null : uPsw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.U_RegisterTime
     *
     * @return the value of users.U_RegisterTime
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public String getuRegistertime() {
        return uRegistertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.U_RegisterTime
     *
     * @param uRegistertime the value for users.U_RegisterTime
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setuRegistertime(String uRegistertime) {
        this.uRegistertime = uRegistertime == null ? null : uRegistertime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.U_Permission
     *
     * @return the value of users.U_Permission
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public Integer getuPermission() {
        return uPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.U_Permission
     *
     * @param uPermission the value for users.U_Permission
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    public void setuPermission(Integer uPermission) {
        this.uPermission = uPermission;
    }
}