package cn.kuqi.Pojo;

import java.util.ArrayList;
import java.util.List;

public class UsersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public UsersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUIdIsNull() {
            addCriterion("U_ID is null");
            return (Criteria) this;
        }

        public Criteria andUIdIsNotNull() {
            addCriterion("U_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUIdEqualTo(Integer value) {
            addCriterion("U_ID =", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotEqualTo(Integer value) {
            addCriterion("U_ID <>", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThan(Integer value) {
            addCriterion("U_ID >", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("U_ID >=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThan(Integer value) {
            addCriterion("U_ID <", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdLessThanOrEqualTo(Integer value) {
            addCriterion("U_ID <=", value, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdIn(List<Integer> values) {
            addCriterion("U_ID in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotIn(List<Integer> values) {
            addCriterion("U_ID not in", values, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdBetween(Integer value1, Integer value2) {
            addCriterion("U_ID between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUIdNotBetween(Integer value1, Integer value2) {
            addCriterion("U_ID not between", value1, value2, "uId");
            return (Criteria) this;
        }

        public Criteria andUNameIsNull() {
            addCriterion("U_Name is null");
            return (Criteria) this;
        }

        public Criteria andUNameIsNotNull() {
            addCriterion("U_Name is not null");
            return (Criteria) this;
        }

        public Criteria andUNameEqualTo(String value) {
            addCriterion("U_Name =", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotEqualTo(String value) {
            addCriterion("U_Name <>", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameGreaterThan(String value) {
            addCriterion("U_Name >", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameGreaterThanOrEqualTo(String value) {
            addCriterion("U_Name >=", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLessThan(String value) {
            addCriterion("U_Name <", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLessThanOrEqualTo(String value) {
            addCriterion("U_Name <=", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameLike(String value) {
            addCriterion("U_Name like", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotLike(String value) {
            addCriterion("U_Name not like", value, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameIn(List<String> values) {
            addCriterion("U_Name in", values, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotIn(List<String> values) {
            addCriterion("U_Name not in", values, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameBetween(String value1, String value2) {
            addCriterion("U_Name between", value1, value2, "uName");
            return (Criteria) this;
        }

        public Criteria andUNameNotBetween(String value1, String value2) {
            addCriterion("U_Name not between", value1, value2, "uName");
            return (Criteria) this;
        }

        public Criteria andUNicknameIsNull() {
            addCriterion("U_Nickname is null");
            return (Criteria) this;
        }

        public Criteria andUNicknameIsNotNull() {
            addCriterion("U_Nickname is not null");
            return (Criteria) this;
        }

        public Criteria andUNicknameEqualTo(String value) {
            addCriterion("U_Nickname =", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotEqualTo(String value) {
            addCriterion("U_Nickname <>", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameGreaterThan(String value) {
            addCriterion("U_Nickname >", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("U_Nickname >=", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameLessThan(String value) {
            addCriterion("U_Nickname <", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameLessThanOrEqualTo(String value) {
            addCriterion("U_Nickname <=", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameLike(String value) {
            addCriterion("U_Nickname like", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotLike(String value) {
            addCriterion("U_Nickname not like", value, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameIn(List<String> values) {
            addCriterion("U_Nickname in", values, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotIn(List<String> values) {
            addCriterion("U_Nickname not in", values, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameBetween(String value1, String value2) {
            addCriterion("U_Nickname between", value1, value2, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUNicknameNotBetween(String value1, String value2) {
            addCriterion("U_Nickname not between", value1, value2, "uNickname");
            return (Criteria) this;
        }

        public Criteria andUSignatureIsNull() {
            addCriterion("U_Signature is null");
            return (Criteria) this;
        }

        public Criteria andUSignatureIsNotNull() {
            addCriterion("U_Signature is not null");
            return (Criteria) this;
        }

        public Criteria andUSignatureEqualTo(String value) {
            addCriterion("U_Signature =", value, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureNotEqualTo(String value) {
            addCriterion("U_Signature <>", value, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureGreaterThan(String value) {
            addCriterion("U_Signature >", value, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("U_Signature >=", value, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureLessThan(String value) {
            addCriterion("U_Signature <", value, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureLessThanOrEqualTo(String value) {
            addCriterion("U_Signature <=", value, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureLike(String value) {
            addCriterion("U_Signature like", value, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureNotLike(String value) {
            addCriterion("U_Signature not like", value, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureIn(List<String> values) {
            addCriterion("U_Signature in", values, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureNotIn(List<String> values) {
            addCriterion("U_Signature not in", values, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureBetween(String value1, String value2) {
            addCriterion("U_Signature between", value1, value2, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUSignatureNotBetween(String value1, String value2) {
            addCriterion("U_Signature not between", value1, value2, "uSignature");
            return (Criteria) this;
        }

        public Criteria andUEmailIsNull() {
            addCriterion("U_Email is null");
            return (Criteria) this;
        }

        public Criteria andUEmailIsNotNull() {
            addCriterion("U_Email is not null");
            return (Criteria) this;
        }

        public Criteria andUEmailEqualTo(String value) {
            addCriterion("U_Email =", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotEqualTo(String value) {
            addCriterion("U_Email <>", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailGreaterThan(String value) {
            addCriterion("U_Email >", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailGreaterThanOrEqualTo(String value) {
            addCriterion("U_Email >=", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLessThan(String value) {
            addCriterion("U_Email <", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLessThanOrEqualTo(String value) {
            addCriterion("U_Email <=", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailLike(String value) {
            addCriterion("U_Email like", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotLike(String value) {
            addCriterion("U_Email not like", value, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailIn(List<String> values) {
            addCriterion("U_Email in", values, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotIn(List<String> values) {
            addCriterion("U_Email not in", values, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailBetween(String value1, String value2) {
            addCriterion("U_Email between", value1, value2, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUEmailNotBetween(String value1, String value2) {
            addCriterion("U_Email not between", value1, value2, "uEmail");
            return (Criteria) this;
        }

        public Criteria andUPswIsNull() {
            addCriterion("U_Psw is null");
            return (Criteria) this;
        }

        public Criteria andUPswIsNotNull() {
            addCriterion("U_Psw is not null");
            return (Criteria) this;
        }

        public Criteria andUPswEqualTo(String value) {
            addCriterion("U_Psw =", value, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswNotEqualTo(String value) {
            addCriterion("U_Psw <>", value, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswGreaterThan(String value) {
            addCriterion("U_Psw >", value, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswGreaterThanOrEqualTo(String value) {
            addCriterion("U_Psw >=", value, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswLessThan(String value) {
            addCriterion("U_Psw <", value, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswLessThanOrEqualTo(String value) {
            addCriterion("U_Psw <=", value, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswLike(String value) {
            addCriterion("U_Psw like", value, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswNotLike(String value) {
            addCriterion("U_Psw not like", value, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswIn(List<String> values) {
            addCriterion("U_Psw in", values, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswNotIn(List<String> values) {
            addCriterion("U_Psw not in", values, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswBetween(String value1, String value2) {
            addCriterion("U_Psw between", value1, value2, "uPsw");
            return (Criteria) this;
        }

        public Criteria andUPswNotBetween(String value1, String value2) {
            addCriterion("U_Psw not between", value1, value2, "uPsw");
            return (Criteria) this;
        }

        public Criteria andURegistertimeIsNull() {
            addCriterion("U_RegisterTime is null");
            return (Criteria) this;
        }

        public Criteria andURegistertimeIsNotNull() {
            addCriterion("U_RegisterTime is not null");
            return (Criteria) this;
        }

        public Criteria andURegistertimeEqualTo(String value) {
            addCriterion("U_RegisterTime =", value, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeNotEqualTo(String value) {
            addCriterion("U_RegisterTime <>", value, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeGreaterThan(String value) {
            addCriterion("U_RegisterTime >", value, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeGreaterThanOrEqualTo(String value) {
            addCriterion("U_RegisterTime >=", value, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeLessThan(String value) {
            addCriterion("U_RegisterTime <", value, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeLessThanOrEqualTo(String value) {
            addCriterion("U_RegisterTime <=", value, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeLike(String value) {
            addCriterion("U_RegisterTime like", value, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeNotLike(String value) {
            addCriterion("U_RegisterTime not like", value, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeIn(List<String> values) {
            addCriterion("U_RegisterTime in", values, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeNotIn(List<String> values) {
            addCriterion("U_RegisterTime not in", values, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeBetween(String value1, String value2) {
            addCriterion("U_RegisterTime between", value1, value2, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andURegistertimeNotBetween(String value1, String value2) {
            addCriterion("U_RegisterTime not between", value1, value2, "uRegistertime");
            return (Criteria) this;
        }

        public Criteria andUPermissionIsNull() {
            addCriterion("U_Permission is null");
            return (Criteria) this;
        }

        public Criteria andUPermissionIsNotNull() {
            addCriterion("U_Permission is not null");
            return (Criteria) this;
        }

        public Criteria andUPermissionEqualTo(Integer value) {
            addCriterion("U_Permission =", value, "uPermission");
            return (Criteria) this;
        }

        public Criteria andUPermissionNotEqualTo(Integer value) {
            addCriterion("U_Permission <>", value, "uPermission");
            return (Criteria) this;
        }

        public Criteria andUPermissionGreaterThan(Integer value) {
            addCriterion("U_Permission >", value, "uPermission");
            return (Criteria) this;
        }

        public Criteria andUPermissionGreaterThanOrEqualTo(Integer value) {
            addCriterion("U_Permission >=", value, "uPermission");
            return (Criteria) this;
        }

        public Criteria andUPermissionLessThan(Integer value) {
            addCriterion("U_Permission <", value, "uPermission");
            return (Criteria) this;
        }

        public Criteria andUPermissionLessThanOrEqualTo(Integer value) {
            addCriterion("U_Permission <=", value, "uPermission");
            return (Criteria) this;
        }

        public Criteria andUPermissionIn(List<Integer> values) {
            addCriterion("U_Permission in", values, "uPermission");
            return (Criteria) this;
        }

        public Criteria andUPermissionNotIn(List<Integer> values) {
            addCriterion("U_Permission not in", values, "uPermission");
            return (Criteria) this;
        }

        public Criteria andUPermissionBetween(Integer value1, Integer value2) {
            addCriterion("U_Permission between", value1, value2, "uPermission");
            return (Criteria) this;
        }

        public Criteria andUPermissionNotBetween(Integer value1, Integer value2) {
            addCriterion("U_Permission not between", value1, value2, "uPermission");
            return (Criteria) this;
        }

        public Criteria andULogincountIsNull() {
            addCriterion("U_LoginCount is null");
            return (Criteria) this;
        }

        public Criteria andULogincountIsNotNull() {
            addCriterion("U_LoginCount is not null");
            return (Criteria) this;
        }

        public Criteria andULogincountEqualTo(Integer value) {
            addCriterion("U_LoginCount =", value, "uLogincount");
            return (Criteria) this;
        }

        public Criteria andULogincountNotEqualTo(Integer value) {
            addCriterion("U_LoginCount <>", value, "uLogincount");
            return (Criteria) this;
        }

        public Criteria andULogincountGreaterThan(Integer value) {
            addCriterion("U_LoginCount >", value, "uLogincount");
            return (Criteria) this;
        }

        public Criteria andULogincountGreaterThanOrEqualTo(Integer value) {
            addCriterion("U_LoginCount >=", value, "uLogincount");
            return (Criteria) this;
        }

        public Criteria andULogincountLessThan(Integer value) {
            addCriterion("U_LoginCount <", value, "uLogincount");
            return (Criteria) this;
        }

        public Criteria andULogincountLessThanOrEqualTo(Integer value) {
            addCriterion("U_LoginCount <=", value, "uLogincount");
            return (Criteria) this;
        }

        public Criteria andULogincountIn(List<Integer> values) {
            addCriterion("U_LoginCount in", values, "uLogincount");
            return (Criteria) this;
        }

        public Criteria andULogincountNotIn(List<Integer> values) {
            addCriterion("U_LoginCount not in", values, "uLogincount");
            return (Criteria) this;
        }

        public Criteria andULogincountBetween(Integer value1, Integer value2) {
            addCriterion("U_LoginCount between", value1, value2, "uLogincount");
            return (Criteria) this;
        }

        public Criteria andULogincountNotBetween(Integer value1, Integer value2) {
            addCriterion("U_LoginCount not between", value1, value2, "uLogincount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}