package cn.kuqi.Pojo;

public class Items {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.id
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.itemName
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    private String itemname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.itemPrice
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    private String itemprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.itemNumber
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    private Integer itemnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.itemPic
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    private String itempic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.id
     *
     * @return the value of items.id
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.id
     *
     * @param id the value for items.id
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.itemName
     *
     * @return the value of items.itemName
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.itemName
     *
     * @param itemname the value for items.itemName
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.itemPrice
     *
     * @return the value of items.itemPrice
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public String getItemprice() {
        return itemprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.itemPrice
     *
     * @param itemprice the value for items.itemPrice
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public void setItemprice(String itemprice) {
        this.itemprice = itemprice == null ? null : itemprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.itemNumber
     *
     * @return the value of items.itemNumber
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public Integer getItemnumber() {
        return itemnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.itemNumber
     *
     * @param itemnumber the value for items.itemNumber
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public void setItemnumber(Integer itemnumber) {
        this.itemnumber = itemnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.itemPic
     *
     * @return the value of items.itemPic
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public String getItempic() {
        return itempic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.itemPic
     *
     * @param itempic the value for items.itemPic
     *
     * @mbg.generated Mon Aug 20 18:28:51 CST 2018
     */
    public void setItempic(String itempic) {
        this.itempic = itempic == null ? null : itempic.trim();
    }
}