package cn.kuqi.Mapper;

import cn.kuqi.Pojo.Advertising;
import cn.kuqi.Pojo.AdvertisingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdvertisingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    long countByExample(AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int deleteByExample(AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int deleteByPrimaryKey(Integer adNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int insert(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int insertSelective(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    List<Advertising> selectByExampleWithBLOBs(AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    List<Advertising> selectByExample(AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    Advertising selectByPrimaryKey(Integer adNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") Advertising record, @Param("example") AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Advertising record, @Param("example") AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByExample(@Param("record") Advertising record, @Param("example") AdvertisingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByPrimaryKeySelective(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Advertising record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertising
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByPrimaryKey(Advertising record);
}