package cn.kuqi.Mapper;

import cn.kuqi.Pojo.ArticleTrample;
import cn.kuqi.Pojo.ArticleTrampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleTrampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    long countByExample(ArticleTrampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int deleteByExample(ArticleTrampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int deleteByPrimaryKey(Integer atNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int insert(ArticleTrample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int insertSelective(ArticleTrample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    List<ArticleTrample> selectByExample(ArticleTrampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    ArticleTrample selectByPrimaryKey(Integer atNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleTrample record, @Param("example") ArticleTrampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByExample(@Param("record") ArticleTrample record, @Param("example") ArticleTrampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByPrimaryKeySelective(ArticleTrample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_trample
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByPrimaryKey(ArticleTrample record);
}