package cn.kuqi.Mapper;

import cn.kuqi.Pojo.ArticleClassfiy;
import cn.kuqi.Pojo.ArticleClassfiyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleClassfiyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    long countByExample(ArticleClassfiyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int deleteByExample(ArticleClassfiyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int deleteByPrimaryKey(Integer acNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int insert(ArticleClassfiy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int insertSelective(ArticleClassfiy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    List<ArticleClassfiy> selectByExample(ArticleClassfiyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    ArticleClassfiy selectByPrimaryKey(Integer acNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleClassfiy record, @Param("example") ArticleClassfiyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByExample(@Param("record") ArticleClassfiy record, @Param("example") ArticleClassfiyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByPrimaryKeySelective(ArticleClassfiy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_classfiy
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByPrimaryKey(ArticleClassfiy record);
}