package cn.kuqi.Mapper;

import cn.kuqi.Pojo.ArticlePraise;
import cn.kuqi.Pojo.ArticlePraiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticlePraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    long countByExample(ArticlePraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int deleteByExample(ArticlePraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int deleteByPrimaryKey(Integer apNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int insert(ArticlePraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int insertSelective(ArticlePraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    List<ArticlePraise> selectByExample(ArticlePraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    ArticlePraise selectByPrimaryKey(Integer apNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticlePraise record, @Param("example") ArticlePraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByExample(@Param("record") ArticlePraise record, @Param("example") ArticlePraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByPrimaryKeySelective(ArticlePraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_praise
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByPrimaryKey(ArticlePraise record);
}