package cn.kuqi.Mapper;

import cn.kuqi.Pojo.Bloginfo;
import cn.kuqi.Pojo.BloginfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BloginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    long countByExample(BloginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int deleteByExample(BloginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int deleteByPrimaryKey(Integer biNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int insert(Bloginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int insertSelective(Bloginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    List<Bloginfo> selectByExample(BloginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    Bloginfo selectByPrimaryKey(Integer biNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") Bloginfo record, @Param("example") BloginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByExample(@Param("record") Bloginfo record, @Param("example") BloginfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByPrimaryKeySelective(Bloginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bloginfo
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByPrimaryKey(Bloginfo record);
}