package cn.kuqi.Mapper;

import cn.kuqi.Pojo.Link;
import cn.kuqi.Pojo.LinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    long countByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int deleteByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int deleteByPrimaryKey(Integer lNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int insert(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int insertSelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    List<Link> selectByExample(LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    Link selectByPrimaryKey(Integer lNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByExample(@Param("record") Link record, @Param("example") LinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByPrimaryKeySelective(Link record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByPrimaryKey(Link record);
}