package cn.kuqi.Mapper;

import cn.kuqi.Pojo.Theme;
import cn.kuqi.Pojo.ThemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    long countByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int deleteByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int deleteByPrimaryKey(Integer tNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int insert(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int insertSelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    List<Theme> selectByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    Theme selectByPrimaryKey(Integer tNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") Theme record, @Param("example") ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByExample(@Param("record") Theme record, @Param("example") ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByPrimaryKeySelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theme
     *
     * @mbg.generated Thu Oct 11 14:40:37 CST 2018
     */
    int updateByPrimaryKey(Theme record);
}