package cn.kuqi.Mapper;

import cn.kuqi.Pojo.TimeUserlogin;
import cn.kuqi.Pojo.TimeUserloginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimeUserloginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    long countByExample(TimeUserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int deleteByExample(TimeUserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int deleteByPrimaryKey(Integer ulNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int insert(TimeUserlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int insertSelective(TimeUserlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    List<TimeUserlogin> selectByExample(TimeUserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    TimeUserlogin selectByPrimaryKey(Integer ulNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") TimeUserlogin record, @Param("example") TimeUserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByExample(@Param("record") TimeUserlogin record, @Param("example") TimeUserloginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByPrimaryKeySelective(TimeUserlogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_userlogin
     *
     * @mbg.generated Tue Dec 04 15:47:06 CST 2018
     */
    int updateByPrimaryKey(TimeUserlogin record);
}